version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8003:8003"
    env_file:
      - .env
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
